---
- hosts: localhost

  vars_files:
    - config.yaml

  tasks:
    - name: What?
      debug:
        msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"

    - include: centos-5-ghost-setup.yaml
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version < '6'

    - include: centos-6-ghost-setup.yaml
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '6'

    - include: centos-7-ghost-setup.yaml
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version > '6'

    - include: ubuntu-14-ghost-setup.yaml
      when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == '14'

    - include: ubuntu-16-ghost-setup.yaml
      when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == '16'

    - include: ubuntu-18-ghost-setup.yaml
      when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == '18'
